### ISSUE TITLE
Help for syntax for options

### ISSUE THREAD

**Issue by colasbd** [StefansArya/LittleYoutube-PHP#1]
Could you give some help for the syntax for options?

This does not work:
```php
$options = 
array(
	"loadVideoSize"=>true,
	"processDetail"=>true
);

$video = LittleYoutube::video("https://www.youtube.com/watch?v=v3nZ7Kmpsms", $options);
```

More code, a full example, might be very helpful (for beginners like me).

Thanks

**Comment by StefansArya** [comment]
Your script is correct, but looks like I put the initialization in wrong order.. 

In the library
`$this->resetInit();`
Should be executed before
`if($options) $this->settings = array_replace($this->settings, $options);`

I will be back in some hours...

**Comment by StefansArya** [comment]
Open this again if you still have an issue
