### ISSUE TITLE
Error 403 

### ISSUE THREAD

**Issue by karrarjasim** [StefansArya/LittleYoutube-PHP#5]
some videos get this (Your client does not have permission to get URL )
any solution?

**Comment by StefansArya** [comment]
Hi, sorry for late respond
Looks like your server was not sending UserAgent header when executing the curl request..

Try modify the script around this function https://github.com/StefansArya/LittleYoutube-PHP/blob/633cb116773fc0f2aa5a1d35da52c3d5b9bcb13e/LittleYoutube.php#L811
