### ISSUE TITLE
Next and previous is error

### ISSUE THREAD

**Issue by gietmxh** [StefansArya/LittleYoutube-PHP#7]
I can't use this

**Comment by StefansArya** [comment]
Looks like everybody needs this feature too, I'm going to fix it then..
#6

**Comment by gietmxh** [comment]
You should add description of video bellow the title in search query

**Comment by gietmxh** [comment]
I think you should see this situation more easily. I think you just get all pagination of search queries. It's very easy. or use &page in url

**Comment by gietmxh** [comment]
https://www.youtube.com/results?search_query=t%E1%BB%9B+th%C3%ADch+c%E1%BA%ADu&page=2

Very simple xD

**Comment by StefansArya** [comment]
Eh, really? o.o
I'm walking on the wrong way lol

**Comment by gietmxh** [comment]
:D I have explore youtube allow use method GET to next page yesterday

**Comment by StefansArya** [comment]
It's implemented now lol

**Comment by gietmxh** [comment]
Maybe you should build a method to get related video :D and in the video parse should show description of video

**Comment by gietmxh** [comment]
That's enough for a good project get data from youtube without api

**Comment by StefansArya** [comment]
Hmm okay, I have some free time right now

**Comment by StefansArya** [comment]
The feature has been [added](https://github.com/StefansArya/LittleYoutube-PHP/wiki/Class:-Video)
